Police-Data-Accessibility-Project/data-source-manager

README.md

[This issue](https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/11) has a giant flowchart which is only updateable in figma by me. I'd rather it be a living diagram for anyone to update and reference.
- adds a mermaid graph to the readme replacing the figma flowchart
- adds agency-identifier to the readme (I noticed it was missing when I was in there)

mermaid graph to readme

---

html_tag_collector/README.md
html_tag_collector/collector.py
html_tag_collector/requirements.txt

* JavaScript-rendered HTML tags can now be rendered by the tag collector instead of being missed.
* The website request infrastructure was overhauled and is now faster + more efficient.
* By default, rendering a page's JavaScript is disabled as it can take a long time (~30 minutes for 1000 links). It can be enabled by passing `render_javascript=True` as a parameter to `collector_main()`
* Tag processing was also parallelized and is now significantly faster.
| url | h1 | h2 | h3 | h4 | h5 | h6
| --- | --- | --- | --- | --- | --- | --- |
| data.cityofnewyork.us/resource/v5jd-6wqn.json | [] | ["Menu"] | [] | [] | [] | [] |
| url | h1 | h2 | h3 | h4 | h5 | h6
| --- | --- | --- | --- | --- | --- | --- |
| data.cityofnewyork.us/resource/v5jd-6wqn.json | ["NYPD Use of Force: Members of Service", …

Overhaul tag collector

---

html_tag_collector/collector.py

Quick update that will strip excess whitespace from html titles collected by the tag collector

Remove html title whitespace

---

html_tag_collector/RootURLCache.py
html_tag_collector/collector.py
html_tag_collector/common.py

* #56 
* All issues outlined in #56 are fixed
* Added some additional whitespace cleanup for `html_title` and `meta_description`
* De-parallelizes the response parser, it takes a little bit longer now (usually about a minute for 200 urls) but this fixes an issue with simultaneous updating of the RootURLCache dictionary.
* Diagnosed and fixed another issue related to the render_javascript functionality, where some websites would refuse the connection due to the user agent not being set properly. This should mean we get even more accurate headers and less errors overall.

Tag collector: root_page_title fixes

---

.github/workflows/common_crawler.yaml
Tests/test_common_crawler_integration.py
common_crawler/README.md
common_crawler/crawler.py
common_crawler/csv_manager.py
common_crawler/main.py

#66 - Common Crawler Enhancements 
This enhances the `common_crawler` module by adding batch logging. Additionally, it modifies the Github Actions yaml file to only run on manual command, rather than automatically.
Run the following unit and integration test scripts located in the `tests` directory.
1. `test_common_crawler_integration.py`
2. `test_common_crawler_unit.py`
3. `test_util_unit.py`
Additionally, follow the instructions in `common_crawler/README.md` to manually run the script and confirm functionality. The script, once completed, should yield the following results:
1. If relevant URLs were found, the new relevant URLs will be located in the aforementioned HuggingFace dataset.
2. The cache should be updated now such that, if the same command is run, the crawler will resume at …

Mc common crawl enhancements

---

.github/workflows/python_checks.yml
Tests/test_type_and_docstyle_checking.py
util/miscellaneous_functions.py
util/type_and_docstyle_checking.py

* Enhances #73 
* The prior implementation include a lot of logic within the yaml file itself and was consequently difficult to debug and prone to unexpected errors.
* The new version migrates the majority of logic into python scripts, where the logic is rendered more comprehensible.
* Additionally, substantial logging has been added, to further improve debugging capabilities.
* Internal testing has been added via `test_type_and_docstyle_checking.py`
Prior testing was demonstrated in the following PRs:
* [This PR](https://github.com/maxachis/Github-Action-Test/pull/1#issuecomment-2043748474), which (after a few modifications) showcases how it would work on a PR
* [This other PR](https://github.com/maxachis/Github-Action-Test/pull/2), which shows it functioning again, but now _only on the …

mc_revise_pr_type_checking_and_linting

---

html_tag_collector/DataClassTags.py
html_tag_collector/collector.py

* #59 
* Changes made according to the original issue
* The `tags` dictionary is converted to a DataClass specified in `DataClassTags.py`
* A unique function is created for each attribute being pulled and for the verification code
1. Clone the repository and checkout the branch
2. Create a virtual environment in the root directory and install the requirements via `requirements.txt`
3. Run `python html_tag_collector/collector.py [test_file.csv]`. 
`test_file.csv` can be any csv with a column labeled 'url' containing a set of urls.

parse_response refactor

---

README.md
common_crawler/README.md
common_crawler/main.py
label_studio_interface/LabelStudioAPIManager.py
requirements.txt

* #83
* URLs that are determined to be duplicates will be removed. This includes URLs being pulled in the same batch and those already in the Label Studio project
* Deduplication ignores http(s)://www.
1. Clone the repository and checkout the `common-crawl-83` branch
2. Setup a virtual environment and install the dependencies via `requirements.txt`
3. Create a `.env` file in the project's root directory. Populate it with the environment variable outlined in the README. The PDAP annotation project ID is 61550 and the organization ID is 9876
4. Run `main.py` as outlined in the README, for example: 
```bash
python common_crawler/main.py CC-MAIN-2023-50 '*.gov' police --config common_crawler/config.ini --pages 2
```

Common crawl deduplication

---

.github/workflows/populate_labelstudio.yml
annotation_pipeline/README.md
annotation_pipeline/config.ini
annotation_pipeline/populate_labelstudio.py
annotation_pipeline/requirements.txt

#96
This PR has tried and true fixes in the manual workflow merged last time. Primarily cleans up path issues that arose from running populate_labelstudio.py in a different location. This also simplifies the output folders for batch_info, cache, and tag collected csv's.
`annotation_pipeline/populate_labelstudio.py`
- path clean up. regardless of manual workflow or running locally, populate_labelstudio.py is now designed to be run from the parent directory (data-source-identification/)
`annotation_pipeline/config.ini`
- new config file for populate_labelstudio to specify save location in annotation_pipeline/data
`annotation_pipeline/README.md`
- updated instructions for running populate_labelstudio locally
`.github/workflows/populate_labelstudio.yml`
- fixes to yaml (string to bool (oops)) …

Annotation Pipeline (manual workflow fixes)

---

alembic/versions/2025_03_11_1539-69f7cc4f56d4_create_approving_user_url_table.py
api/routes/review.py
collector_db/AsyncDatabaseClient.py
collector_db/models.py
core/AsyncCore.py
tests/test_automated/integration/collector_db/test_db_client.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/151

feat(app): add table to record users validating URLs.

---

collector_db/AsyncDatabaseClient.py
collector_db/StatementComposer.py
tests/test_automated/integration/collector_db/test_db_client.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/177

fix(database): Fix bug causing validated URLs to show up for some annotations

---

collector_db/AsyncDatabaseClient.py
tests/helpers/complex_test_data_functions.py
tests/test_automated/integration/api/test_annotate.py
tests/test_automated/integration/collector_db/test_db_client.py

Previously, the `/annotate/agencies` `POST` method would return a 500 error when an agency whose ID was not yet in the DBI database was submitted. This has been resolved.
https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/190

feat(database): add agency not in database in annotate agencies

---

ENV.md
api/main.py
core/AsyncCore.py
tests/test_automated/integration/api/conftest.py
tests/test_automated/integration/core/test_async_core.py
tests/test_automated/integration/security_manager/test_security_manager.py
util/DiscordNotifier.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/204
The task loop has been modified such that, if prerequisites continue to be met, the same task loop will run again.
In the case of the task looping more than 20 times, the task loop is set to break and discord notified as an indicator of potentially unwelcome activity.

feat(app): enable task loop to repeat if prerequisites met

---

api/main.py
collector_db/AsyncDatabaseClient.py
collector_manager/AsyncCollectorBase.py
collector_manager/AsyncCollectorManager.py
core/AsyncCoreLogger.py
core/SourceCollectorCore.py
source_collectors/auto_googler/AutoGooglerCollector.py
source_collectors/muckrock/classes/MuckrockCollector.py
tests/manual/source_collectors/test_autogoogler_collector.py
tests/manual/source_collectors/test_ckan_collector.py
tests/manual/source_collectors/test_common_crawler_collector.py
tests/manual/source_collectors/test_muckrock_collectors.py
tests/test_automated/integration/api/conftest.py
tests/test_automated/integration/api/test_batch.py
tests/test_automated/integration/api/test_example_collector.py
tests/test_automated/integration/conftest.py
tests/test_automated/integration/core/test_example_collector_lifecycle.py
tests/test_automated/unit/source_collectors/test_autogoogler_collector.py
tests/test_automated/unit/source_collectors/test_ckan_collector.py
tests/test_automated/unit/source_collectors/test_common_crawl_collector.py
tests/test_automated/unit/source_collectors/test_example_collector.py
tests/test_automated/unit/source_collectors/test_muckrock_collectors.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/204

feat(app): make logger async

---

api/routes/task.py
collector_db/DTOs/GetTaskStatusResponseInfo.py
collector_db/enums.py
core/AsyncCore.py
core/TaskManager.py
core/classes/URLHTMLTaskOperator.py
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_task.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/212

feat(app): add task status endpoint

---

alembic/versions/2025_04_17_0909-e285e6e7cf71_change_batch_completed_to_ready_to_label.py
collector_db/StatementComposer.py
collector_db/models.py
collector_manager/AsyncCollectorBase.py
core/TaskManager.py
core/enums.py
tests/manual/core/lifecycle/test_auto_googler_lifecycle.py
tests/manual/core/lifecycle/test_ckan_lifecycle.py
tests/manual/core/lifecycle/test_common_crawler_lifecycle.py
tests/manual/core/lifecycle/test_muckrock_lifecycles.py
tests/test_automated/integration/api/test_example_collector.py
tests/test_automated/integration/core/test_async_core.py
tests/test_automated/integration/core/test_example_collector_lifecycle.py
util/alembic_helpers.py

feat(app): change batch status `completed` to `ready to label`

---

api/routes/batch.py
collector_db/AsyncDatabaseClient.py
core/AsyncCore.py
tests/helpers/DBDataCreator.py
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_batch.py
tests/test_automated/integration/collector_db/test_db_client.py

feat(app): Add `/batch` filter for batches with pending URLs

---

collector_db/AsyncDatabaseClient.py
tests/helpers/DBDataCreator.py
tests/test_automated/integration/api/test_batch.py

#228
Previously, `has_pending_urls` was returning multiple instances of the same batches in some cases. This has been resolved.

fix(database): fix duplicate bug in `/batch` get for `has_pending_urls`

---

collector_db/DTOConverter.py
core/enums.py

fix(app): Change suggestion type `MANUAL_SUGGESTION` to `USER_SUGGESTION`

---

api/main.py

#160 
Additionally, add redirect at `/docs` endpoint to redirect user to `/api` route.

docs(api): Change `/docs` to `/api` for API display

---

source_collectors/auto_googler/AutoGooglerCollector.py

#221
Consolidate environment variable usage through a centralized class, to enable easy mocking and tracking of environment variables.

refactor(app): consolidate environment variable usage

---

core/classes/task_operators/URLRelevanceHuggingfaceTaskOperator.py
hugging_face/HuggingFaceInterface.py
hugging_face/relevancy_worker.py
tests/manual/huggingface/test_hugging_face_interface.py
tests/test_automated/integration/tasks/test_url_relevancy_huggingface_task.py

refactor(app): refactor to reduce memory strain from huggingface task

---

api/main.py
collector_manager/ExampleCollector.py
tests/helpers/AwaitableBarrier.py
tests/helpers/patch_functions.py
tests/test_automated/integration/api/conftest.py
tests/test_automated/integration/api/test_duplicates.py
tests/test_automated/integration/api/test_example_collector.py
tests/test_automated/integration/core/test_example_collector_lifecycle.py
tests/test_automated/unit/core/test_core_logger.py

implement techniques to simulate extended periods of time, instead of simply running things for those periods of time.
#222

refactor(tests): reduce time required to run time-bound tests

---

api/main.py
collector_db/AsyncDatabaseClient.py
collector_db/DatabaseClient.py
core/ScheduledTaskManager.py
core/SourceCollectorCore.py
tests/test_automated/integration/collector_db/test_db_client.py
tests/test_automated/integration/conftest.py

#241
Additionally, because now the Scheduled Task Manager is no longer in use, it has been removed and references to it removed.

feat(app): make delete logs job an asynchronous scheduled task

---

api/routes/annotate.py
collector_db/AsyncDatabaseClient.py
collector_db/StatementComposer.py
core/AsyncCore.py
core/DTOs/AllAnnotationPostInfo.py
core/DTOs/GetNextRecordTypeAnnotationResponseInfo.py
core/DTOs/GetNextURLForAllAnnotationResponse.py
core/DTOs/GetNextURLForAnnotationResponse.py
core/exceptions.py
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_annotate.py
tests/test_automated/unit/dto/test_all_annotation_post_info.py

#183
Create endpoints for receiving and submitting all annotations for a URL at once.

feat(app): Create `/annotation/all` endpoints

---

alembic/versions/2025_05_03_0956-028565b77b9e_add_manual_strategy_to_batch_strategy_.py
api/routes/collector.py
collector_db/AsyncDatabaseClient.py
collector_db/DatabaseClient.py
collector_db/models.py
collector_manager/enums.py
core/AsyncCore.py
core/DTOs/ManualBatchInputDTO.py
core/DTOs/ManualBatchOutputDTO.py
core/DTOs/ManualBatchResponseDTO.py
pyproject.toml
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_manual_batch.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/200

Mc 200 manual batches

---

api/main.py
api/routes/search.py
collector_db/AsyncDatabaseClient.py
core/AsyncCore.py
core/DTOs/SearchURLResponse.py
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_search.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/254

feat(app): Add `/search/url` endpoint

---

core/AsyncCore.py
core/classes/ErrorManager.py
core/enums.py
core/helpers.py
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_annotate.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/171

feat(app): Add special error message for annotation user conflict

---

alembic/versions/2025_05_11_1054-9d4002437ebe_set_default_created_at_for_backlog_.py
collector_db/AsyncDatabaseClient.py
core/TaskManager.py
hugging_face/HuggingFaceInterface.py
hugging_face/relevancy_worker.py
local_database/classes/DockerContainer.py
tests/helpers/DBDataCreator.py
tests/test_automated/integration/tasks/test_agency_preannotation_task.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/255
Previously, agency identification was erroneously pulling up URLs that had an error status. This has been addressed.

fix(app): Address bug in agency identification

---

alembic/versions/2025_05_13_0704-864107b703ae_create_url_checked_for_duplicate_table.py
collector_db/AsyncDatabaseClient.py
collector_db/enums.py
collector_db/models.py
core/DTOs/task_data_objects/URLDuplicateTDO.py
core/TaskManager.py
core/classes/task_operators/URLDuplicateTaskOperator.py
pdap_api_client/DTOs.py
pdap_api_client/PDAPClient.py
tests/test_automated/integration/tasks/conftest.py
tests/test_automated/integration/tasks/test_submit_approved_url_task.py
tests/test_automated/integration/tasks/test_url_duplicate_task.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/198

feat(app): add url duplicate check task operator

---

alembic/versions/2025_05_13_1234-b5f079b6b8cb_create_url_probed_for_404_table_and_.py
collector_db/AsyncDatabaseClient.py
collector_db/DTOConverter.py
collector_db/enums.py
collector_db/models.py
collector_manager/enums.py
core/DTOs/task_data_objects/URL404ProbeTDO.py
core/DTOs/task_data_objects/UrlHtmlTDO.py
core/TaskManager.py
core/classes/task_operators/URL404ProbeTaskOperator.py
core/classes/task_operators/URLHTMLTaskOperator.py
html_tag_collector/URLRequestInterface.py
tests/manual/html_collector/test_html_tag_collector_integration.py
tests/test_automated/integration/tasks/test_url_404_probe.py
tests/test_automated/integration/tasks/test_url_html_task.py
util/alembic_helpers.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/117
Add 404 Probe Task
Additionally update HTML Task to add 404 status to URL where 404s are returned

feat(app): Add 404 Probe Task

---

alembic/versions/2025_05_16_1031-00cc949e0347_update_relevancy_logic.py
api/routes/annotate.py
api/routes/review.py
collector_db/AsyncDatabaseClient.py
collector_db/DTOConverter.py
collector_db/models.py
collector_manager/enums.py
core/AsyncCore.py
core/DTOs/AllAnnotationPostInfo.py
core/DTOs/FinalReviewApprovalInfo.py
core/DTOs/GetNextURLForFinalReviewResponse.py
core/DTOs/RelevanceAnnotationPostInfo.py
core/enums.py
tests/helpers/DBDataCreator.py
tests/helpers/test_batch_creation_parameters.py
tests/test_automated/integration/api/helpers/RequestValidator.py
tests/test_automated/integration/api/test_annotate.py
tests/test_automated/integration/api/test_metrics.py
tests/test_automated/integration/api/test_review.py
tests/test_automated/integration/collector_db/test_db_client.py
tests/test_automated/unit/dto/test_all_annotation_post_info.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/223
Overhaul rejection/relevancy annotation logic 
Update `/annotate/relevance/{url_id}` to accept `relevant`, `not relevant`, `broken page`, `single_record` entries
Update `/annotate/all/{url_id}` to do the same
Update `/review/reject-source` to allow specification of a `rejection_reason` including `not relevant`, `broken page`, and `single record`
Update database such that URL have status `rejected` replaced with `not relevant` and add additional status `individual record`

Mc 223 relevancy labeling

---

src/api/main.py
src/core/tasks/manager.py
src/core/tasks/operators/agency_identification/core.py
tests/automated/integration/collector_db/test_db_client.py
tests/automated/integration/core/test_async_core.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/305

Refactor to remove redundant ClientSession creation in `agency_identification`

---

src/core/tasks/scheduled/sync/agency/operator.py
src/core/tasks/url/operators/submit_approved_url/queries/get.py
src/core/tasks/url/operators/submit_approved_url/queries/has_validated.py
src/core/tasks/url/operators/submit_approved_url/queries/mark_submitted.py
src/db/client/async_.py

Migrate more database logic to query builder from direct db client access. 
Set so that if a specific URL creates an error in processing, the url id is listed, allowing more targeted (and faster) inspection.

Reform url validation logic and add better error notification.

---

alembic/versions/2025_08_11_0914-c14d669d7c0d_change_link_table_nomenclature.py
src/db/models/instantiations/url/data_source/sqlalchemy.py

https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/336

Change name of url_data_sources to url_data_source

---

src/api/main.py
src/core/tasks/url/operators/submit_approved/queries/cte.py
src/core/tasks/url/operators/submit_approved/queries/get.py
src/core/tasks/url/operators/submit_approved/queries/has_validated.py
src/db/models/impl/batch/sqlalchemy.py
tests/automated/integration/tasks/url/impl/submit_approved/test_submit_approved_url_task.py
tests/conftest.py

https://github.com/Police-Data-Accessibility-Project/data-source-manager/issues/416

Fix bug in URL Submit Approved Task, update test

---

alembic/versions/2025_09_15_1137-d5f92e6fedf4_add_location_tables.py
src/db/models/helpers.py
src/db/models/impl/link/agency_location/sqlalchemy.py
src/db/models/impl/location/county/sqlalchemy.py
src/db/models/impl/location/locality/sqlalchemy.py
src/db/models/impl/location/location/enums.py
src/db/models/impl/location/location/sqlalchemy.py
src/db/models/impl/location/us_state/sqlalchemy.py
src/db/models/mixins.py

https://github.com/Police-Data-Accessibility-Project/data-source-manager/issues/423

mc_423_add_location_tables

---

alembic/versions/2025_09_26_1357-b9317c6836e7_add_agency_and_jurisdiction_type.py
src/api/endpoints/review/approve/query_/core.py
src/db/client/async_.py
src/db/models/impl/agency/enums.py
src/db/models/impl/agency/sqlalchemy.py
tests/automated/integration/api/review/test_approve_and_get_next_source.py
tests/automated/integration/tasks/url/impl/submit_approved/setup.py
tests/automated/integration/tasks/url/impl/submit_approved/test_submit_approved_url_task.py
tests/helpers/data_creator/core.py

mc_425_agency_search_endpoint

---

src/api/endpoints/search/agency/models/response.py
src/api/endpoints/search/agency/query.py
src/db/models/impl/agency/sqlalchemy.py

Add additional attributes for agency search

---

alembic/versions/2025_10_04_1640-f708c6a8ae5d_remove_unused_batches_columns.py
pyproject.toml
src/core/tasks/url/operators/record_type/llm_api/record_classifier/base.py
src/db/client/async_.py
src/db/client/sync.py
src/db/models/impl/batch/sqlalchemy.py
src/db/statement_composer.py
uv.lock

https://github.com/Police-Data-Accessibility-Project/data-source-manager/issues/259

mc_426_remove_agencies_location_columns

---

src/external/internet_archives/client.py
tests/manual/external/internet_archive/test_upload.py

mc_387_internet_archives_save
